### ISSUE TITLE
The speed of training

### ISSUE THREAD

**Issue by wangwenchao-job** [tensorflow/models#10163]
My problem is that the training is very slow.

I changed my custom project by referring to the example in Project.

Here is my configuration file

```
runtime:
  distribution_strategy: 'mirrored'
  # mixed_precision_dtype: 'float16'
  loss_scale: 'dynamic'
  num_gpus: 1
task:
  model:
    num_classes: 2
    input_size: [128, 128, 3]
    backbone:
      type: 'vggnet'
      vggnet:
        model_id: 'vggnet16'
      pre_model_dir:
        dir: '~/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5'
      represent_dim:
        dim: '1'
    norm_activation:
      # activation: 'mish'
      activation: 'sigmod'
  losses:
    l2_weight_decay: 0.0005
    one_hot: true
  train_data:
    tfds_name: 'my_dataset'
    tfds_split: 'train'
    tfds_data_dir: '~/tensorflow_datasets/'
    is_training: true
    global_batch_size: 16  # default = 128
    dtype: 'float16'
    shuffle_buffer_size: 100
  validation_data:
    tfds_name: 'my_dataset'
    tfds_split: 'validation'
    tfds_data_dir: '~/tensorflow_datasets/'
    is_training: true
    global_batch_size: 16  # default = 128
    dtype: 'float16'
    drop_remainder: false
    shuffle_buffer_size: 100
trainer:
  train_steps: 104720  # 80 epochs
  validation_steps: 50
  validation_interval: 1309
  steps_per_loop: 1309  # NUM_EXAMPLES (1281167) // global_batch_size
  summary_interval: 1309
  checkpoint_interval: 1309

  # train_steps: 6400000  # epochs: 80, 800000 * 128/batchsize
  # validation_steps: 3200  # size of validation data, 400 * 128/batchsize
  # validation_interval: 10000  # 10000
  # steps_per_loop: 10000
  # summary_interval: 10000
  # checkpoint_interval: 10000
  optimizer_config:
    # optimizer:
    #   type: 'sgd'
    #   sgd:
    #     momentum: 0.9
    optimizer:
      type: 'rmsprop'
      rmsprop:
        rho: 0.9
        momentum: 0.9
        epsilon: 0.0000007
        clipnorm: 1.0
    learning_rate:
      type: 'polynomial'
      polynomial:
        initial_learning_rate: 0.00005  # 0.1 * batchsize/128, default = 0.1
        end_learning_rate: 0.0000125  # 0.0001 * batchsize/128, default = 0.0001
        power: 4.0
        decay_steps: 104720  # 790000 * 128/batchsize,   default =  800000 - 1000 = 799000
    warmup:
      type: 'linear'
      linear:
        warmup_steps: 1047  # 0 to 0.1 over 1000 * 128/batchsize, default = 128

```
I have the following questions:

1. How is the epoch calculated in our project? I refer to this file official/vision/beta/configs/experiments image_classification/imagenet_mobilenetv2_gpu yaml, The calculation appears to be epoch = train_steps // steps_per_loop. But that's not how it seems to work in yOLO

2. Does the activation function have SIGMOD? I did not find sigMOD in the source code

3. I can start gpu training, what do you want to ask or report this warning
![a2227e991eaa53bb10c6bede505e42e](https://user-images.githubusercontent.com/57739867/127172765-e4ff9449-b9ab-4b1d-a448-514f6c63b59a.png)
4. Why is it very slow to output the results of a training session? The interval between the two outputs is 1 minute

also， My environment is:

Tf against 2.4.1

gpu 1080ti

Ubuntu 18.04
