### ISSUE TITLE
SSD mobilenet v3 converted to tflite with postprocessing does not work correctly on the device

### ISSUE THREAD

**Issue by AndrzejKRK** [tensorflow/models#8237]
The problem is that: I export the [ssd_mobilenet_v3_large_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_large_coco_2019_08_14.tar.gz) model to a graph along with postprocessing.

```
python object_detection/export_tflite_ssd_graph.py \
--pipeline_config_path ssd_mobilenet_v3_large_coco_2019_08_14/pipeline.config \
--trained_checkpoint_prefix ssd_mobilenet_v3_large_coco_2019_08_14/model.ckpt \
--output_directory ssd_mobilenet_v3_large_coco_2019_08_14/tflite \
--add_postprocessing_op=true
```

Next, I get a graph such as a .pb file with post-processing

Then I convert the previously obtained graph into a float tflite model using the following script: 
```
tflite_convert \
--graph_def_file=tflite/tflite_graph.pb \
--output_file=tflite/frozen_inference_graph_test.tflite \
--output_format=TFLITE \
--input_arrays=normalized_input_image_tensor \
--input_shapes=1,320,320,3 \
--output_arrays="TFLite_Detection_PostProcess,TFLite_Detection_PostProcess:1,TFLite_Detection_PostProcess:2,TFLite_Detection_PostProcess:3" \
--allow_custom_ops
```
I use the converted model in my Android application, but I don’t get the correct results, always at the output I get strange results:

```
D/DEBUGMODELANSWEAR:  
     SCORES: 0.116135836 CLASS: 14.0
     SCORES: 0.046395004 CLASS: 0.0
     SCORES: 0.045846403 CLASS: 0.0
     SCORES: 0.045446068 CLASS: 0.0
     SCORES: 0.04536411 CLASS: 0.0
     SCORES: 0.04513964 CLASS: 0.0
     SCORES: 0.045139074 CLASS: 0.0
     SCORES: 0.04456976 CLASS: 14.0
     SCORES: 0.044314265 CLASS: 0.0
     SCORES: 0.044303298 CLASS: 0.0
```

Interestingly, I do the same actions with [ssd_mobilenet_v3_small_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_small_coco_2019_08_14.tar.gz), but this model works fine. Can someone tell me what I'm doing wrong and how can I fix this situation

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac
- Mobile device (e.g., Pixel 4, Samsung Galaxy 10) if the issue happens on mobile device: Xiaomi mi 9
- TensorFlow installed from (source or binary):  pip
- TensorFlow version (use command below): v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Tflite mobile: 'org.tensorflow:tensorflow-lite:0.0.0-nightly'
- Python version: 3
- Bazel version (if compiling from source):  not applicable
- GCC/Compiler version (if compiling from source): not applicable
- CUDA/cuDNN version: not applicable
- GPU model and memory: not applicable

1. TensorFlow 1.0
v1.14.0-rc1-22-gaf24dc91b5 1.14.0
