### ISSUE TITLE
What is the "pattern" in train_file_pattern? 

### ISSUE THREAD

**Issue by chudur-budur** [tensorflow/models#9827]
# Prerequisites

Please answer the following question for yourself before submitting an issue.

- [x] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the documentation with the issue

https://github.com/tensorflow/models/blob/master/official/vision/detection/README.md

## 2. Describe the issue

In one of the yaml configs, it says:

```
# my_retinanet.yaml
type: 'retinanet'
train:
  train_file_pattern: <path to the TFRecord training data>
eval:
  eval_file_pattern: <path to the TFRecord validation data>
  val_json_file: <path to the validation annotation JSON file>
```

In my case, the TFRecords are saved as 

```
coco_train.record-00039-of-00100    coco_val.record-00039-of-00050
coco_train.record-00040-of-00100    coco_val.record-00040-of-00050
coco_train.record-00041-of-00100    coco_val.record-00041-of-00050
coco_train.record-00042-of-00100    coco_val.record-00042-of-00050
coco_train.record-00043-of-00100    coco_val.record-00043-of-00050
coco_train.record-00044-of-00100    coco_val.record-00044-of-00050
coco_train.record-00045-of-00100    coco_val.record-00045-of-00050
... etc.
```

and the "pattern" I am supplying is like `train_file_pattern='coco_train.record-?????-of-00100'`. 

Is this correct?
